### ISSUE TITLE
University Logo not to be centered on page

### ISSUE THREAD

**Issue by mgkuhn** [cambridge/thesis#11]
The University Logo, consisting of the shield and the "UNIVERSITY OF CAMBRIDGE" text to the right of it, was not designed to be used in the centre of the page (as you currently do on the title page). It actually looks pretty painful to me when used centred near other centred text, as it is highly asymmetric in a symmetric structure. If you want to use the full logo, it really belongs into a corner of the page (Communications Office suggest top-left or top-bottom).

https://www.cam.ac.uk/brand-resources/guidelines/using-the-logo

**Comment by urbas** [comment]
Indeed, it does look a bit off. I will try to move it to the left (with the prescribed left margin).

**Comment by urbas** [comment]
The logo is now nudged to the left. The fix was part of pull request #24 (see [this change](https://github.com/cambridge/thesis/pull/24/files#diff-6d7f3647138d9a704ec8e776b431f42eR350)).
