### ISSUE TITLE
Margin widths don't match those suggested by J S Wilson

### ISSUE THREAD

**Issue by bderrett** [cambridge/thesis#23]
I notice that, when the document is not a technical report, the odd, even, top and bottom margins are  35mm, 30mm, 35mm, 25mm, respectively, while J S Wilson [suggests](http://www.jswilsonandson.co.uk/thesis-binding/) 30mm, 20mm, 20mm and 20mm. You might want to change the margins to match this recommendation if there isn't a good reason why they don't. Thanks for this template, by the way -- it has saved me a lot of time!

**Comment by urbas** [comment]
Thanks for finding this one, and apologies for the late reply.

The proposed fix is in pull request #28. 

Here's how the pages look like with the fix:

- [plain thesis](https://bintray.com/matej/cam-thesis/download_file?file_path=thesis-43-25869a80.pdf)

- [sample Clean](https://bintray.com/matej/cam-thesis/download_file?file_path=sample-clean-43-25869a80.pdf)

**Comment by urbas** [comment]
Fix is now in master (merged PR #28).
