### ISSUE TITLE
For hardbound thesis: abstract page should include the dissertation title and author name

### ISSUE THREAD

**Issue by chatcannon** [cambridge/thesis#38]
http://www.cambridgestudents.cam.ac.uk/your-course/examinations/graduate-exam-information/submitting-and-examination/phd-msc-mlitt/submit#hardbound

What are the requirements for the hardbound submission?

The minimum requirements for the Hardbound thesis are as follows:
* [... omitted requirements for the binding process ...]
* a completed Deposit and Copying of Dissertation Declaration Form - this form must be bound inside each copy of the thesis as the very first page - that is, before the title page. [...]
* a copy of your Summary/Abstract with your name and dissertation title on it. This must be bound inside the thesis following the title page

**Comment by chatcannon** [comment]
You could also add an option to prepend the "Deposit and Copying" form to the document.

**Comment by chatcannon** [comment]
I am currently using the hacky solution of
```tex
\abstract{
\section*{$TITLE}
\subsection*{$NAME}

... abstract text ...
}
```

**Comment by urbas** [comment]
Both of these must be handed in separately. They say so in the page you linked.

Look for the bold text saying "Loose with the thesis (not bound inside) you must provide the following".

**Comment by chatcannon** [comment]
It says there needs to be an extra copy of the abstract handed in separately, but also says it needs a copy of the abstract with name and title **bound inside the thesis following the title page**

**Comment by chatcannon** [comment]
On the other hand, I wouldn't be surprised if the information on the web page is wrong. I certainly was criticised by my examiners when I complied with the wording of the declaration by noting *both in the preface and in the text* every occasion when something was the result of collaboration etc.

**Comment by urbas** [comment]
Oh, yes, sorry about that! I glanced over that a bit too quickly.

I think your snippet is pretty reasonable. Feel free to add it to `cam-thesis.cls` directly.

However, I think it's worth checking with the Student Registry whether this is mandatory&mdash;given that the title and the name of the author are already printed on the title page and the declaration form. It feels a bit redundant. I'll send them an email and let you know.

**Comment by urbas** [comment]
I got an answer from the student registry. Here's the response:

> The title and name of the author must be on the loose copy of the abstract as stated in the guidelines.

I guess we don't have to add the name and the title then.

Btw, I suggested to update the guidelines (to make it a bit clearer).

**Comment by urbas** [comment]
I think it's okay to omit the declaration form for now.

Please reopen if you'd still like to include the declaration.
