### ISSUE TITLE
Suggestion about glossary layout

### ISSUE THREAD

**Issue by tjiagoM** [cambridge/thesis#42]
I suggest to change the line 142 of `cam-thesis.cls` to the following:

```latex
\newcommand{\printthesisglossary}{\printglossary[nonumberlist]}
```
Basically I added the option `nonumberlist` to `\printglossary`. I think that what is useful is to have just a list of names for the glossary, there's no need to have all the page numbers with the places where the names are used. This might turn in a ugly glossary page if the name is used everywhere in the thesis.

**Comment by urbas** [comment]
Is this needed only when you use `backref`? I cannot see the page numbers on the current master: https://63-1710676-gh.circle-artifacts.com/0/cam-thesis/build/pdfs/thesis.pdf

**Comment by tjiagoM** [comment]
Currently, for each glossary item, the pages where that glossary item is used are printed. For example, in that `thesis.pdf`, you have "HOL Higher-order logic. 13". You have the number 13 indicating where the acronym is used. If you start writing several `\gls{HOL}` on the document, the page numbers will continue and continue to grow, and I think in a glossary index you just need to have the list of acronyms and explanations, right?
(So, I think it's not a problem of using `backref`)

**Comment by urbas** [comment]
Yes, it will get a bit annoying. Thanks a bunch for the clarification.
