### ISSUE TITLE
Suggestion for bibliography

### ISSUE THREAD

**Issue by tjiagoM** [cambridge/thesis#45]
What about changing the bibliography style from `plain` to `plainnat`?
This would allow us to use some handy things like `\citeauthor{}`
What do you think, @urbas ?

**Comment by urbas** [comment]
I think `plain` is a bit safer default choice as it produces shorter citation references (see [this PDF](https://67-1710676-gh.circle-artifacts.com/0/cam-thesis/build/pdfs/thesis.pdf)) and (from what I've seen) it is a more commonly use citation style in Computer Lab's PhD theses.

Users can still change that, but I'd vote to leave `plain` as default.

I'll close this for now. We can reopen if more people vote on this one.

**Comment by chatcannon** [comment]
For what it's worth, I used `unsrtnat`, which sorted the references in the correct order for Chemistry theses, but had to edit the .bib files to remove all fields which shouldn't appear in the bibliography, and also to standardise names (e.g. only initials and surname). In the process, I discovered that BibTeX files downloaded from publishers are often full of errors, so going over them manually should be necessary anyway.

**Comment by tjiagoM** [comment]
@chatcannon You can try JabRef because it has an option to create the bibtex from the DOI, or similar tool online, I had the same problem as you: http://www.doi2bib.org/#/doi

**Comment by tjiagoM** [comment]
@urbas I've been searching a bit about the differences between `plain` and `plainnat` and as far as I could understand `plainnat` is basically `plain` plus some useful stuff. 

I'm definitely using `plainnat` now because while I'm writing it is very useful to use stuff like `\citeauthor{}`, but can you please explain what you meant by "it produces shorter ciration references"? Because I tried with both `plainnat` and `plain` and couldn't find any difference in my bibliography section.

**Comment by urbas** [comment]
@tjiagoM: if you look at the first paragraph on page 13 of [this PDF](https://67-1710676-gh.circle-artifacts.com/0/cam-thesis/build/pdfs/thesis.pdf) you'll see the long author list of the citation (the PDF was generated from [this commit](https://github.com/cambridge/thesis/commit/079e165c855a5f01c13237bef7b1882dfea0265b)). The citation in this example uses `\cite{example}` and `\bibliographystyle{plainnat}`.

Shorter citation styles (that look like `[1]`) cause fewer line-overfullness problems, that's why I'd vote for `plain`.

**Comment by tjiagoM** [comment]
Ah, now I get it. But that's why I use `\usepackage[numbers]{natbib}` when i want the `plainnat` option.

This way I have the same things as `plain` with the perks that I mentioned in the beginning, without any side effects, I think.

**Comment by urbas** [comment]
I see now. Yes that definitely sounds good. :+1: Reopening this issue. Btw, feel free to create a PR for this.

**Comment by urbas** [comment]
PR #47 addressed this issue.
