### ISSUE TITLE
Question about crests

### ISSUE THREAD

**Issue by tjiagoM** [cambridge/thesis#48]
Hi, just a quick question: is there any reason to have many different formats for the crests when only PDF is actually used? In my last commit I actually put both PDFs and SVGs but actually it seems I didn't need to. And as PDF is also a vector document (like svg), nothing is lost, right? :p

**Comment by urbas** [comment]
Some time ago we actually built converted SVGs into other formats. We don't do this anymore, so I think it's okay if we remove them.

**Comment by urbas** [comment]
@tjiagoM resolved this issue in PR #49.
