### ISSUE TITLE
Use package microtype

### ISSUE THREAD

**Issue by tjiagoM** [cambridge/thesis#50]
I've come to some words that went outside the document's margin and the problem was solved by including a package that I have been using until now: `microtype`. I want to suggest to include that in the `.cls` style file. What do you think?

A link with some highlights of the package: http://www.khirevich.com/latex/microtype/
(It really shows a lot of parameters we can benefit from the package, but only its inclusion seems already very positive)

**Comment by urbas** [comment]
I'd say it is okay if the package is included in a typical distribution of texlive. For example, in this repository we use Ubuntu 16.04 and packages `texlive` and `texlive-latex-extra`. Give it a try and let's see how our samples look like.

**Comment by tjiagoM** [comment]
Yes, microtype is included in a typical repository. In my case solved everything. Ok, I will make a PR and you can see, also :)

**Comment by tjiagoM** [comment]
I didn't forget this Issue. I'm just waiting for the other pull request so I don't mix everything.

**Comment by urbas** [comment]
Microtype is now in, closing the ticket.
