### ISSUE TITLE
Suggestion on solving some underfull \vbox

### ISSUE THREAD

**Issue by tjiagoM** [cambridge/thesis#51]
In my report I got some pages in which the paragraphs had to be stretched to fill the whole page. This meant that some unexpected spaces between paragraphs appeared. Searching a little bit, it seems the correct way to handle this situation is using the `\raggedbottom` option (which, in my case, completely solved my problem).

Using this command means that the pages might not have all the same size in terms of text content. But in the case of reports like this one, it seems it is much nicer to have a regular space between paragraphs rather than some pages with stretched paragraphs.

What do you think?

**Comment by urbas** [comment]
[This doc](http://www.rpi.edu/dept/arc/docs/latex/latex-intro.pdf) mentions that the `\raggedbottom` is the default for reports when using `twoside` (which is what our cam-thesis uses by default).

Can you check why it wasn't used in your case?

**Comment by tjiagoM** [comment]
Honestly, I don't know, but it's not working. I cloned the repository and tried directly with the .cls that it is in the repository.

With `\raggedbottom` somewhere in the cls file:
![image](https://user-images.githubusercontent.com/7031523/28020465-7d2b7e9a-657c-11e7-9edf-1be8a3bde0bb.png)



With the original .cls from the repository without modifications:
![image](https://user-images.githubusercontent.com/7031523/28020490-93b6626a-657c-11e7-8075-bc5a427da86c.png)



I reproduced this behaviour in this file (had to change to .txt so I could upload it, but it is a tex file):
[thesis.txt](https://github.com/cambridge/thesis/files/1135640/thesis.txt)

**Comment by tjiagoM** [comment]
Hum, I looked to the link you mention and what I see is not `\raggedbottom` by default in the `twoside` option:

> \flushbottom is the default for the book class and for the twoside option in the article and report
classes

**Comment by urbas** [comment]
@tjiagoM: oh my, sorry about that. It's good you double-checked. Feel free to include it in the .cls file. It does look better with consistent vertical spacing.

**Comment by urbas** [comment]
raggedbottom is now in, closing the issue.
