### ISSUE TITLE
.cls missing files

### ISSUE THREAD

**Issue by sanjeevhiremath** [cambridge/thesis#61]
Hi,
I am trying to use Cambridge thesis template for First-year submission. However, when is change tag to \documentclass[withindex,glossary]{firstyr}, Overleaf is reporting an error saying firstyr.cls is missing.

cls files are missing

**Comment by urbas** [comment]
You have to specify the option like this:
```
\documentclass[firstyr,withindex,glossary]{cam-thesis}
```

Here's an example: https://github.com/cambridge/thesis/blob/master/.circleci/tests/firstyr/thesis.tex#L1

**Comment by sanjeevhiremath** [comment]
Thanks. it works. Closing this issue.
