### ISSUE TITLE
University of Cambridge logo should not be added to the title page

### ISSUE THREAD

**Issue by urbas** [cambridge/thesis#70]
@RyanGibb reports that the University of Cambridge has banned their arms/shield/logo appearing on PhD dissertations.

>    Please note that the University logo should not be used as your thesis is your work and not the work of the University. If you wish to use a logo on your title page, you are advised to ask your College about the use of their logo.[0]

[0] https://www.cambridgestudents.cam.ac.uk/your-course/examinations/graduate-exam-information/submitting-and-examination/phd-msc-mlitt/submit

**Comment by tjiagoM** [comment]
That sentence has been removed from the link, so the repo's template is (again) correct :)
