### ISSUE TITLE
Command \printindex already defined

### ISSUE THREAD

**Issue by eouti** [cambridge/thesis#8]
Hello,
i'm really would like to use this thesis template, but i get an error while trying to compile the sources.
I have no idea what to do, even tried to remove \printindex occurences, but doesn't work neither.
Here's the full output of my error : 

$ make
NOTE: You may ignore warnings about the following files:
     thesis.d
Makefile:2556: thesis.d: No such file or directory
= thesis.tex --> thesis.d thesis.pdf.1st.make (0-1) =
= thesis.glo --> thesis.gls =
= thesis.idx --> thesis.ind =
= thesis.tex --> thesis.d thesis.pdf.1st.make (1-1) =
= thesis.bib thesis.aux --> thesis.bbl =
/usr/share/texlive/texmf-dist/tex/latex/glossaries/base/glossaries.sty:1413: LaTeX Error: Command \printindex already defined.
               Or name \end... illegal, see p.192 of the manual.
make: *** [thesis.pdf] Error 1

It gives the same \printindex issue when using makepdf or makeps.

Thanks for help,

eoutin

**Comment by ic3guy** [comment]
Steffen's fix worked for me to. Same thing happened, for my submission everything worked fine, but then for corrections errors popped up. I'm guessing I upgraded my latex distribution in the interim.

**Comment by mgkuhn** [comment]
A proper fix (rather than an ugly workaround) would be to rename the "index option: #15
